# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  first-job:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Greeting
        run: echo "Hello Jyothi...!"

      # Runs a set of commands using the runners shell
      - name: Print Good Bye
        run: echo "Bye Jyothi...!"

